services:
  app:
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
      VIRTUAL_PORT: "${APP_INTERNAL_PORT}"
networks:
  proxy:
    external: true
    name: "${PROXY_NETWORK:-nginx-proxy}"
